### ISSUE TITLE
Static link exception not mentioned in the source/header files

### ISSUE THREAD

**Issue by JohnnyNj** [stachenov/quazip#101]
The COPYING file contains a static linking exception which seems to permit static linking to a closed source application as long as that application is an "independent module". But, that exception is not mentioned in the source files. Should it be?

**Comment by stachenov** [comment]
Probably... but I'd *really* hate to change every source file just because of that. Is it really necessary, legal-wise, considering that the sources aren't the definitive license location and they *do* reference COPYING?

**Comment by JohnnyNj** [comment]
Thanks for an incredibly quick answer. I am not sure about the legal stuff either. Maybe just state in the COPYING file that the exceptions applies to all the source/header files even if not directly stated there. Or maybe you could do the change to one of the source/header files, and I could help making the same change to all the other source files (and learn github and pull-requests).

**Comment by stachenov** [comment]
It doesn't really take that much effort to update every source file. I'd dislike to do it not because it's a hassle, but because it messes up history. For example, `quazip.cpp` was modified exactly 6 times since the project's migration to GitHub in 2018. The last modification was in August, which is not that long time ago, but it wasn't yesterday either. And *that* was only because it was a massive update, touching almost every source file because it was replacing `NULL` with `nullptr` everywhere.

It's not *that* much of a problem, but *does* add unnecessary noise to the history, which I'd like to avoid if possible.

Changing COPYING is acceptable, though. I'll do it.

**Comment by JohnnyNj** [comment]
Thanks alot.

**Comment by stachenov** [comment]
The change is there. Is it enough?

**Comment by JohnnyNj** [comment]
Perfect :)
