### ISSUE TITLE
CMake minimal version

### ISSUE THREAD

**Issue by dbrgn** [stachenov/quazip#104]
Hi, thanks for maintaining quazip!

I read through the issue trackers relating to the qmake > cmake port. I'm currently going through the same thing, we're porting LibrePCB from qmake to cmake and I've already spent many days on it :smile: 

Regarding quazip, I think I'm already on a very good path. We want to provide a vendored quazip by default (using `add_subdirectory`), but fall back to system quazip if the vendored version wasn't found (or if a corresponding variable is set). This [already works quite nicely](https://github.com/LibrePCB/LibrePCB/blob/cmake/cmake/FindQuaZip.cmake) on my Arch Linux machine.

However, the library doesn't currently build with Ubuntu 16.04 because that ships with CMake 3.5. We're trying to support version 3.5+, so I'll have to find a solution for that issue.

In commit e32b3db65909230f52cd0fe5d536c7e1af77adbb, you added the minimal CMake version 3.15. That won't even compile on Ubuntu 18.04, which is in LTS until 2023. The reason given is that `GNUInstallDirs` is only required on 3.15+. However, from reading the docs, it seems that GNUInstallDirs was already supported on 3.5? https://cmake.org/cmake/help/v3.5/module/GNUInstallDirs.html

Do you remember whether there were other issues with CMake <3.15? If not, would you be willing to accept a PR that changes the minimal version to 3.5?

I'd also be willing to contribute GitHub CI configuration to run the builds on Ubuntu 16/18/20. It seems that there's no CI right now. To me, as a maintainer of a few open source projects, CI gives me a lot of peace of mind when accepting PRs, because I can be pretty sure that they don't break anything :slightly_smiling_face:

**Comment by stachenov** [comment]
3.15 was indeed chosen because of GNUInstallDirs. I'm not sure where I got this idea that 3.15 was needed for it. I'll look into it.

However, prior to that the candidate for the minimum version was 3.14 for some other reason. Don't remember that either, will look into it too.

As far as various distros are concerned... I was really reluctant to advance CMake version even past 2.8 because that's the version RHEL/CentOS 7 ships with, and it's supported until 2024! I am usually very reluctant to drop any legacy support (QuaZip still works with Qt 4.x after all!). But old style CMake was really ugly and messy, *and* installation of modern cmake is more or less just download-and-run. No complicated dependencies, no special setups, nothing. So between really painful support of CMake 2.8 and moving on to modern CMake I just had to choose the latter. And once that move is made, it doesn't really matter whether it's 3.5, 3.14, 3.15 or 3.19... There is always a mainstream distro that will lack even 3.1 (I've already mentioned RHEL 7 above).

If a distro ships with an outdated version of CMake, then I think there are two ways do deal with it: either upgrade CMake version (seriously, Ubuntu 18.04 is not a stable commercial distro like RHEL 7, and CMake is insanely backwards compatible, so why not upgrade?) or introduce a downstream patch for QuaZip that makes it somehow compile with that outdated CMake version.

That being said, however, if there is a way to lower CMake version requirement without much pain, then it makes sense to lower it to a reasonable value. I'll look into CMake version history and think about it. Not promising anything, though.

Re: CI, I have never dealt with CI. I don't get that many PRs, so just running the test suite manually works for me just fine. But it certainly won't harm either.

**Comment by stachenov** [comment]
Update: here's why 3.14 was considered:

https://github.com/stachenov/quazip/issues/82#issuecomment-661252204

> default locations for the install(TARGETS command based on the GNUInstallDirs package were only added in 3.14

So it's not like GNUInstallDirs was added in 3.14, but rather the default paths were set to those determined by GNUInstallDirs. And I certainly don't want to code them manually now, going back past 3.14.

I couldn't find any reason why 3.15 was chosen, though. But I don't see any reason to downgrade to 3.14 now either. Too little difference to matter.

3.14 also introduced some changes to how finding Qt works:

https://cmake.org/cmake/help/latest/release/3.14.html

> The FindQt module is no longer used by the find_package() command as a find module. This allows the Qt Project upstream to optionally provide its own QtConfig.cmake package configuration file and have applications use it via find_package(Qt) rather than find_package(Qt CONFIG). See policy CMP0084.

I don't know whether it's important or not, or when it is important, but I'd rather not risk it.

If 3.5, 3.10 or whatever ancient version works just fine on a certain distro, then it's just a matter of a downstream patch that changes just a single line. But doing that globally, for all users, with whatever crazy environments they might have... no, I don't think it's a right way to do, especially now that 1.0 is out and it's considered very stable.

**Comment by dbrgn** [comment]
Ok, I can see why that decision makes sense for you :slightly_smiling_face: Since we link LibrePCB statically against Quazip when using the vendored version, we can probably patch this ourselves. Feel free to close this issue!
