### ISSUE TITLE
Possibility to build without QTextCodec

### ISSUE THREAD

**Issue by xlazom00** [stachenov/quazip#151]
I would like to propose idea that we can build quazip without QTextCodec.
- with some cmake switch
- checking qt if qt has QTextCodec support

as in Qt6 QTextCodec is deprecated

And there is also option to add support for QStringDecoder
I found this 
**QStringDecoder vs QTextCodec** 
![](https://user-images.githubusercontent.com/550020/120161037-91b03e80-c1ff-11eb-9cb5-2ebd11a2e4cd.png)

**Comment by xlazom00** [comment]
So something like this?
https://github.com/Memsource/quazip/pull/1/files

**Comment by oblivioncth** [comment]
Qt 6.4 is enabling QStringConverter to use any encoding provided by ICU when Qt is built with ICU support enabled.

https://doc-snapshots.qt.io/qt6-dev/whatsnew64.html
https://doc-snapshots.qt.io/qt6-dev/qstringconverter.html#encodingForName

In the long run this is probably the preferred alternative for handling encodings that were previously deprecated by Qt6, rather than a manual switch like the above (though they can certainly coexist). Build Qt with ICU support, get extended encoding support in QuaZip.

This would allow dropping the Qt5Compat module as a requirement when using Qt6 outright.

**Comment by cen1** [comment]
Closing in favor of a more recent https://github.com/stachenov/quazip/issues/184
