### ISSUE TITLE
Can't build on MacOS

### ISSUE THREAD

**Issue by iajrz** [stachenov/quazip#23]
Running `qmake && make` errors out; turns out this is happening because zlib isn't being added to the LIBS, so the linker doesn't know what to do about it.

Changing [quazip/quazip.pro](https://github.com/stachenov/quazip/blob/d5eaa8be998da2430ffd43e0eefa617cf1550ca3/quazip/quazip.pro) to include the lib when mac is detected fixes this.

**Comment by iajrz** [comment]
If anyone finds this in the future: the flag to tell the linker what zip library to use is missing. Just add it. In my case, adding `LIBS+= -lz` to the `.pro` file worked, given I had zlib installed.

**Comment by stachenov** [comment]
As a side note, the docs actually mention additional parameters to `qmake` right here:
https://stachenov.github.io/quazip/
But they focus more on paths, not on exact libraries. I'll edit them shortly to better reflect most popular setups (`-lz` on MacOS X, `-lzlibwapi` on MSVC and so on).

As another side note, in most cases it's actually better to use `qmake` parameters rather than editing the `.pro` file. The `.pro` file may get overwritten on the next update and these parameters are machine-specific anyway. The only exception I can think of is when you have your own fork tweaked to a specific platform.

**Comment by iajrz** [comment]
I am rather new to C++, so the customs and patterns are still a work in progress for me. I must confess I read the page you linked until I found MacOS X was not in the list of supported platforms, then immediately went elsewhere to look for info.

Thanks a lot for this information, and for maintaining this project.
