### ISSUE TITLE
quazip password protect an archive

### ISSUE THREAD

**Issue by Avenger2209** [stachenov/quazip#58]
Hello, I hope it's the good place to ask this, because I'm new on Github and I'm not sure where to ask this.

I've imported QuaZip in my Qt project and I can easily compress a folder including files to zip.
Now I'd like to protect this zip file with a password but I don't find the solution.

Could you please tell me if it's possible?
Thanks a lot

**Comment by stachenov** [comment]
It is possible, although probably not as easy. If you used `JlCompress`, then it doesn't support passwords right now. You can either use `QuaZip` and `QuaZipFile` to compress it manually (see tests in qztest for examples), or add an appropriate overload in `JlCompress` (you can even send a PR through GitHub so that other people can use your overload too).
