### ISSUE TITLE
Suggestion: Update cmake files to "modern cmake"

### ISSUE THREAD

**Issue by asmaloney** [stachenov/quazip#68]
The cmake files require a very old version of cmake (2.8.5 from 2011) and this makes it difficult to use within other projects. Right now it cannot directly be included as a subdirectory and we must write our own cmake file for it.

I would suggest moving to a more recent version of cmake (3.8+) and to use targets properly so it's easier to add to projects.

**Comment by stachenov** [comment]
Perfect timing. Various CMake updates, pending for v1.0, are currently being discussed at PR #60. Will consider this one too.

**Comment by asmaloney** [comment]
Great!

I've just spent a month or so learning and rewriting all the cmake for [CloudCompare](https://github.com/CloudCompare/CloudCompare) to follow the [modern cmake style](https://cliutils.gitlab.io/modern-cmake/). Not quite done yet, but I'm now on our plugins which is where I ran into quazip.

Once you move to targets, cmake actually starts to make more sense :-)

**Comment by stachenov** [comment]
I finally found some time to start learning CMake. I've just started, so I can't do anything meaningful yet, but as a part of learning process, I looked at CMake versions available in different environments. I'm afraid I have some bad news here: CentOS 7 (and therefore RHEL 7 too) has CMake 2.8.12.2 bundled. RHEL 7 is supported until at least 2024. That's very bad news because we can't just jump to modern CMake and ignore major distros.

As an option, it's possible to require at least CMake 3.8, and force everyone who doesn't have it to use qmake... But that's a risky way, I wouldn't do it unless I knew exactly how many people/distros depend on being able to use CMake 2.8.

**Comment by vaerizk** [comment]
@stachenov

**Comment by stachenov** [comment]
Good, it'll be a great help for 1.0. The work there seems to be stalling, so maybe this'll help.

**Comment by stachenov** [comment]
I've created #82 for CMake-related discussion. It's now spread among several issues/PRs, some of which are closed, and that makes hard to keep track of all those and search for them. Please don't post here any more.

**Comment by jlgranda** [comment]
Hi @stachenov thank you, no is problem of quazip (it's a rock). The problems will be https://github.com/android/ndk/issues/1069.
