### ISSUE TITLE
Didn't you consider supporting qmake?

### ISSUE THREAD

**Issue by CrawlWu** [stachenov/quazip#87]
Now that the qt library has been used，could you consider adding .pro files for **qmake** to use?

**Comment by jannkoeker** [comment]
qmake support was recently ditched in commit 1cf777c97705bf932e95dda6c2c8824b12f994e8

**Comment by stachenov** [comment]
That's right. I strongly considered leaving qmake there. I didn't want support CMake. I didn't even want to learn it. But it turned out users needed it. That it's the de-facto standard build system for C/C++. So I had to learn it in the end.

Then I considered supporting both qmake and CMake. But that turned out to be very confusing. The two systems are very different and maintaining both in a consistent manner would be very problematic. For example, if someone were to send me a PR for CMake, I'd need to make sure I do the same thing with qmake if possible, and do my best to figure out the best compromise otherwise. The worst part is that qmake install wouldn't contain CMake config files, so it would be *very* problematic for CMake users (and most of the users *are* CMake users) to use QuaZip that someone else installed using qmake.

Of course, the other option was to leave both in an inconsistent state, just maintain them independently. That's exactly what the situation was with 0.x, and by the end it confused everyone. Nobody knew what the right include paths were, or what the binary would be named because CMake and qmake builds had very different ideas about those.

So ditching qmake was the only sensible option in the end. Qt 6 is rumored to use CMake as the main build system. Qt 5 supports it too. Qt Creator supports it. And CMake itself supports Qt 4. Using CMake, on the other hand, is as simple as download-and-install. Nothing prevents you from using QuaZip from a qmake project either, just specify the right library and include paths and link to the library.

Read #60 and #82 if you're interested in historic details.

**Comment by CrawlWu** [comment]
@stachenov Yes,you are right,We should be ready to embrace **cmake**.But the documentation's section **Build...** still uses **qmake**.

**Comment by stachenov** [comment]
Where exactly? If you're referring to GitHub pages, they are updated every release. 1.0 isn't released yet. The latest docs can be built by running `doxygen` in the project root, the output will be in `doc/html`. The only place qmake is mentioned now is where I explain why CMake should now be used instead.

**Comment by CrawlWu** [comment]
[doc mainpage](https://stachenov.github.io/quazip/),Section-Building, testing and installing. The footer of page displays that Generated on Wed Apr 29 2020 17:09:53, it should be before switching to cmake.

**Comment by stachenov** [comment]
And the title says quazip-0.9. As I’ve mentioned, the docs are updated every release. 1.0 wasn’t released yet. You can easily build the latest docs from source.
