### ISSUE TITLE
Are these classes reentrant or thread safe？

### ISSUE THREAD

**Issue by CrawlWu** [stachenov/quazip#88]
In some scenarios, I may need to read or write compressed packages in parallel, so I made this suggestion.

**Comment by stachenov** [comment]
A good question! Guess I should clarify it in the docs. Yes, QuaZip is mostly reentrant. The only exceptions are obviously static variables, but there are only few of them. One is used by the encryption part of Minizip, but as far as I can see, it is only used to ensure that the random number generator is only initialized once. I'm not sure if that has any security consequences, but apparently it has none.

QuaZip itself only uses static variables to set some global defaults, such as `QuaZip::setDefaultFileNameCodec` and `QuaZip::setDefaultOsCode`. These are supposed to be set before you even begin to do anything with ZIP files, and if you do so, there won't be any reentrancy issues.

Other that these specific features, QuaZip is as reentrant as any library with class-private mutable state fields is. That is, don't use the same instance concurrently, and you'll be fine.

**Comment by CrawlWu** [comment]
Thanks for your patience all the time.

**Comment by RichardTea** [comment]
QuaZip is re-entrant but not thread-safe.
The exceptions are the global default setters, which are neither rentrant nor thread-safe.

I use a wrapper around each QuaZip instance to ensure I don't try to read or write from the same QuaZip Zipfile instance.

Note that it's fundamentally unsupportable to read and write from the same zipfile at the same time, because you would be racing the operating system.

**Comment by CrawlWu** [comment]
@RichardTea I mean to read or write from the different QuaZip Zipfile instance from multiple threads at once. Read I have tried it's ok, I don't know if Write is safe or valid, from the QuaZipFile's constructor, seem no support. Maybe I also need to have a try.

**Comment by stachenov** [comment]
If these are *different* instances, then there should be no problem whatsoever because they are completely independent, except for a few global variables, which are modified through static setters (like setting a default codec for file names or OS code). If you need to call any, be sure to do it before you begin any parallel work, and you'll be fine. I'll mention the details in the docs for 1.0, which should be released soon enough.

**Comment by CrawlWu** [comment]
If parallel writing is supported, `QuaZipFile::QuaZipFile ( const QString & zipName,const QString & fileName, QuaZip::CaseSensitivity cs = QuaZip::csDefault, QObject * parent = nullptr )` may should be used for **write**(now doc says read only) access also. The original doc usage almost implies the use of the same QuaZip instance.

**Comment by RichardTea** [comment]
Parallel usage of the same QuaZIP instance is **not** supported.

Parallel writing of the same underlying file is **not** supported, and is not possible to support.

Parallel reading from the same underlying file is supported by using separate QuaZIP instances.

**Comment by stachenov** [comment]
Parallel writing to different files using different QuaZip instances *is* supported, though. If a constructor is for read only use, just use another constructor. I don't remember why exactly that constructor is for reading only. Perhaps more information is needed to open a ZIP archive for writing, and hence a separate instance of `QuaZip` is needed. Just use different `QuaZip/QuaZipFile` pairs to write to different ZIP files and you'll be fine.

**Comment by RichardTea** [comment]
When you construct a QuaZipFile without passing it a QuaZip object in the constructor, QuaZipFile creates an internal QuaZip instance using the default options.

The internal one is hidden from you because it will be deleted when the QuaZipFile is deleted or QuaZipFile::setZip() called - thus holding the pointer would be extremely bad!

This means there's no way for you to configure the global settings for the containing ZIP file.

While this isn't a fundamental technical limitation, I think it is very sensible to require users of the library to be clear about the difference between the enclosing "QuaZip" instance and the QuaZipFiles inside.

**Comment by stachenov** [comment]
QuaZip is really badly designed in this sense. It was a mistake to begin with to have this `QuaZip/QuaZipFile` pair because there can be only one `QuaZipFile` instance per `QuaZip` instance. And I'm not really an expert on documentation writing either, so maybe the docs aren't very clear in some parts. If anyone has any sensible correction ideas, some PRs would be very helpful and welcome.

**Comment by CrawlWu** [comment]
> Parallel writing to different files using different QuaZip instances _is_ supported, though. If a constructor is for read only use, just use another constructor. I don't remember why exactly that constructor is for reading only. Perhaps more information is needed to open a ZIP archive for writing, and hence a separate instance of `QuaZip` is needed. Just use different `QuaZip/QuaZipFile` pairs to write to different ZIP files and you'll be fine.

@stachenov @RichardTea Parallel writing by using different QuaZip instances will cause the loss of written data, files or file data are possible. I guess it may be caused by `close()` of QuaZip from a certain thread finish it's work ahead of time.

**Comment by stachenov** [comment]
No, no, no.

If you're using different thread-local instances, writing to different ZIP files, and *not* using encryption (which is not reentrant in Minizip), you're fine.

Of course, if your program is not correctly written in the first place, then QuaZip reentrancy won't help. For example, if you forcibly terminate a thread (which one should probably *never* do) or incorrectly pass objects between threads (for example, creating a QuaZip instance in thread's constructor). I didn't exactly get your phrase about `close()` from a certain thread, but it sounds alarming. A QuaZip instance creation, use and closing should happen in a single thread. That's what reentrancy is about.

**Comment by CrawlWu** [comment]
I may not express what I mean clearly, I mean using different thread-local instances, and suspect that the close of the same file(archive file) is not reentrant at the system level. My test result is that data will be lost, which behave as if the write buffer is overwritten.

**Comment by stachenov** [comment]
I may not express what I mean clearly, either...

Using
A. *different;*
B. *thread-local* instances;
C. for writing to *different* ZIP files
is safe.

Using either
A. *the same* instance from *different threads;*
B. *different* instances for writing to *the same* ZIP archive;
is *not* safe.

**Comment by CrawlWu** [comment]
Ok, it's clearly now.
