### ISSUE TITLE
Can't read file from inside archive(QuaZip) in a archive(QuaZip).

### ISSUE THREAD

**Issue by CrawlWu** [stachenov/quazip#96]
Demo as following,
```
QuaZip outterZip(this->zipFile);
outterZip.open(QuaZip::mdUnzip);
outterZip.setCurrentFile(exp.originalFileName);
QuaZipFile originalZip(&outterZip);
//                QuaZipFile originalZip(this->zipFile, exp.originalFileName);
if(originalZip.open(QIODevice::ReadOnly))
{
	QuaZip innerZip(&originalZip);
	if(innerZip.open(QuaZip::mdUnzip))
	{
		innerZip.setCurrentFile(imgFile);

		QuaZipFile zipImg(&innerZip);
		QImage image;
		if(zipImg.open(QIODevice::ReadOnly))
		{
			image.loadFromData(zipImg.readAll());
		}
		wellDrpltImgs.append(image);
	}
}
```
I got the following error,
> QWARN  : QuaZip::setCurrentFile(): ZIP is not open in mdUnzip mode
> QWARN  : QuaZipFile::open(): file open mode 1 incompatible with ZIP open mode 0

**Comment by CrawlWu** [comment]
Related to 
> https://github.com/stachenov/quazip/issues/36
Found that many compression software support this feature.

**Comment by stachenov** [comment]
I'm not sure how it's possible at all. It's always possible to just read the whole thing into a `QBuffer` and then simply open it as a `QuaZip`. But without that... Reading a ZIP file requires constant seeking back and forth, and that's not quite possible when a ZIP is inside another archive because compression by itself is not compatible with seeking (at least not deflate). Maybe with certain kinds of archives it is possible to implement a very limited support of something like that.

Most software simply extract the inner archive into a temporary directory and then work with it. It's just equally possible with QuaZip. Just like reading it into a `QBuffer`, if you have enough RAM to spare. But sequential reading on the fly... No, that's not possible.

**Comment by CrawlWu** [comment]
I use

**Comment by stachenov** [comment]
Re: `setFileName()`, that code doesn't make much sense. It's just a regular use of a `QuaZip / QuaZipFile` pair. Go to next file, then simply create a `QuaZipFile zipFile(&zip)`, or `QuaZipFile zipFile; zipFile.setZip(&zip)`. It doesn't really matter. The call to `setFileName()` is totally unnecessary because the current file is *already* set by `goToFirstFile() / goToNextFile()`, and it's that current file is what will be opened with `QuaZipFile` when `open()` is called. Simply remove the `setFileName()` and you'll should be fine.

Your second error is really confusing. It should open just fine. Check `getZipError()` after `open()`. Perhaps the buffer contents are somehow wrong.

And could you please stop spamming me with these constant close, open, close, open, close, open...?

**Comment by CrawlWu** [comment]
Sorry, I'm upset. open then `getZipError()` return -1000.

**Comment by stachenov** [comment]
That, indeed, means that the archive can't be opened for some reason. Unfortunately, the exact error is not reported by Minizip, but you can try writing your buffer into a temporary file and then look at it. Perhaps open it with a 3rd party software, check it for corruption.

**Comment by CrawlWu** [comment]
`~QuaZip()` will crash will use as the following scene:
    QuaZip originalFilezip;

    QuaZipFile insideZip(this->zipFile, exps.at(0).originalFileName);
    QBuffer bufInsideZip;
    if(insideZip.open(QIODevice::ReadOnly))
    {
        QByteArray ba = insideZip.readAll();
        bufInsideZip.setBuffer(&ba);

        originalFilezip.setIoDevice(&bufInsideZip);
        if(!originalFilezip.open(QuaZip::mdUnzip))
        {
            qWarning("loadDrpltImages():unzip original file failed!");
        }
    }

**Comment by stachenov** [comment]
Posting random snippets won't really help here. There is nothing in it to suggest what `this->zipFile` might be, how it is initialized, what state it is in, is there any concurrency at work, etc. And since this is C++, there is no guarantee that there was no memory corruption at any point even before this snippet begins executing.

What is really needed is an MCVE/MRE/MWE: a minimal, stand-alone example of self-sufficient code, along with a sample ZIP file that can be just downloaded, compiled, and it would demonstrate the crash right away. *Then* I'd have something to work on.

**Comment by CrawlWu** [comment]
Yeah, I have updated my comment.

**Comment by stachenov** [comment]
Works for me... Tested on Windows 10 / MinGW32 with Qt 5.15.0 and Qt 5.12.9. Have you tested that the MCVE above really crashes? Just with that code and that very ZIP file? On what platform?

**Comment by CrawlWu** [comment]
Sorry, I missed some key details. We need to trigger `~QuaZip()`. I have updated complete `main()` code, note for the parentheses inside.

**Comment by stachenov** [comment]
Nope, still doesn't crash. And besides, the destructor will be called anyway on function exit, so the extra braces don't really change anything.

That particular code just runs forever because `a.exec()` enters the event loop. If I just replace it with `return 0`, the program exists cleanly.

And you still haven't told the details: what is the platform, any specific build options?

**Comment by CrawlWu** [comment]
Windows 10 / VS2019 with Qt 5.15.0

**Comment by stachenov** [comment]
All right... So I've downloaded MSVS 2019 Community, installed Qt5.15.0/MSVC2019 x64, and managed to build the whole thing, including your MCVE. Nope. Still no crash at all. Tried both release and debug. Obviously there is something wrong with your setup, and I have no clue what it could be.

**Comment by CrawlWu** [comment]
Okay, I am using release 1.0 and just run the demo above. I mark the problem firstly, and post my call stack. I will use the latest code to compile into a library, then do a test.
![image](https://user-images.githubusercontent.com/9069122/99370079-302a2180-28f8-11eb-9276-8f00833beeaf.png)

**Comment by stachenov** [comment]
Funny enough, it *does* crash on Linux! Looking into it...

**Comment by stachenov** [comment]
Ah... got it. `bufInsideZip` is declared *after* `originalFilezip`, which means it is destroyed *before*. And the destructor tries to close the underlying device, which doesn't exist anymore, thus leading to a crash.

There are several solutions. The best in this case, I think, is to disable the auto-close completely by calling `originalFilezip.setAutoClose(false)`, maybe right after the declaration.

It is even documented here:
https://stachenov.github.io/quazip/classQuaZip.html#a7a4323b73e12f3b4470109f200728f9f

**Comment by CrawlWu** [comment]
So it is. Recommending to provide different interfaces to distinguish whether close the underlying device. Reference to `QByteArray` how to distinguish whether release buf.
